### ISSUE TITLE
Customization String for cSHAKE

### ISSUE THREAD

**Issue by kc2rxo** [ahmadkhanfar/DET#1]
The customization string for cSHAKE MUST be the following hex value for DET generation:

```
0x00B5 A69C 795D F5D5 F008 7F56 843F 2C40
```

This is known as the "Context ID".

The input for cSHAKE is `Prefix + HID + Suite ID + Public Key`

https://github.com/ahmadkhanfar/DET/blob/56770aa98949ff9bbd4d5a5c908ed1f5beeca4f9/DET.ino#L46

**Comment by ahmadkhanfar** [comment]
The cShake is now taking Prefix + HID + Suite ID + Public Key, check the h_orchid_left
