### ISSUE TITLE
Bit length of RAA/HDA

### ISSUE THREAD

**Issue by kc2rxo** [ahmadkhanfar/DET#2]
How many bits does `String(var, BIN)` return? RAA and HDA are explicitly 14 bits in length.

https://github.com/ahmadkhanfar/DET/blob/56770aa98949ff9bbd4d5a5c908ed1f5beeca4f9/DET.ino#L42

**Comment by ahmadkhanfar** [comment]
Defined a struct for RAA, HDA, which now they will be 14 bits.
