### ISSUE TITLE
DET generation issues

### ISSUE THREAD

**Issue by kc2rxo** [ahmadkhanfar/DET#3]
https://github.com/ahmadkhanfar/DET/blob/56770aa98949ff9bbd4d5a5c908ed1f5beeca4f9/DET.ino#L40
DET is 16 bytes, not 32 bytes. An IPv6 address is 128-bits long.

https://github.com/ahmadkhanfar/DET/blob/56770aa98949ff9bbd4d5a5c908ed1f5beeca4f9/DET.ino#L44
Input data MUST include the public key

https://github.com/ahmadkhanfar/DET/blob/56770aa98949ff9bbd4d5a5c908ed1f5beeca4f9/DET.ino#L49
The lower half (8 bytes, 64 bits) of a DET is the result of the cSHAKE operation. The upper bits are Prefix + HID + OGA ID.

**Comment by ahmadkhanfar** [comment]
new code DET example 

2001:003F:FE04:0105:c740:e6a8:da13:c463
